In [1]:
import pandas as pd

# 1. Historical VaR

First, load data from `data/varData.csv` using `pandas`:

In [9]:
Data = pd.read_csv("data/varData.csv")

This is a portfolio of 4 assets: Dow Jones index, FTSE index, CAC index, and Nikkei index.

In [10]:
Data.head() # first few rows

row       date      DJIA     FTSE-500       CAC-40       Nikkei
0    0   7-Aug-06  11219.38  6026.332958  4345.083562  14023.43535
1    1   8-Aug-06  11173.59  6007.081161  4347.992701  14300.91343
2    2   9-Aug-06  11076.18  6055.300076  4413.353201  14467.08611
3    3  10-Aug-06  11124.37  5964.003963  4333.898171  14413.32157
4    4  11-Aug-06  11088.02  5977.008283  4338.859931  14270.95226

In [11]:
Data.tail() # last few rows

row       date      DJIA     FTSE-500       CAC-40       Nikkei
496  496  18-Sep-08  11019.69  4806.292767  3878.771078  11658.00254
497  497  19-Sep-08  11388.44  5269.607790  4246.994928  11878.44496
498  498  22-Sep-08  11015.69  5227.512359  4214.237071  12049.82757
499  499  24-Sep-08  10825.17  5109.668623  4113.333213  12159.59156
500  500  25-Sep-08  11022.06  5197.000000  4226.810000  12006.53000

Assume now we are at the end of date 25-Sep-2008 and we wanna predict the expected DJIA tomorrow (on 26-Sep-2008) using historical data of this index in the previous 501 dates. From the previous 501 DJIA's index price, we can get 500 return observations.

In [12]:
Data['djiaRet'] = Data['DJIA']/Data['DJIA'].shift(1)

In [13]:
Data

row       date      DJIA     FTSE-500       CAC-40       Nikkei   djiaRet
0      0   7-Aug-06  11219.38  6026.332958  4345.083562  14023.43535       NaN
1      1   8-Aug-06  11173.59  6007.081161  4347.992701  14300.91343  0.995919
2      2   9-Aug-06  11076.18  6055.300076  4413.353201  14467.08611  0.991282
3      3  10-Aug-06  11124.37  5964.003963  4333.898171  14413.32157  1.004351
4      4  11-Aug-06  11088.02  5977.008283  4338.859931  14270.95226  0.996732
..   ...        ...       ...          ...          ...          ...       ...
496  496  18-Sep-08  11019.69  4806.292767  3878.771078  11658.00254  1.038647
497  497  19-Sep-08  11388.44  5269.607790  4246.994928  11878.44496  1.033463
498  498  22-Sep-08  11015.69  5227.512359  4214.237071  12049.82757  0.967269
499  499  24-Sep-08  10825.17  5109.668623  4113.333213  12159.59156  0.982705
500  500  25-Sep-08  11022.06  5197.000000  4226.810000  12006.53000  1.018188

[501 rows x 7 columns]

From that 500 return observations, we have 500 possible scenarios to predict the tomorrow DJIA:

In [28]:
Data['djiaForecast'] = Data['DJIA'][500] * Data['djiaRet']
Data

row       date      DJIA     FTSE-500       CAC-40       Nikkei  \
0      0   7-Aug-06  11219.38  6026.332958  4345.083562  14023.43535   
1      1   8-Aug-06  11173.59  6007.081161  4347.992701  14300.91343   
2      2   9-Aug-06  11076.18  6055.300076  4413.353201  14467.08611   
3      3  10-Aug-06  11124.37  5964.003963  4333.898171  14413.32157   
4      4  11-Aug-06  11088.02  5977.008283  4338.859931  14270.95226   
..   ...        ...       ...          ...          ...          ...   
496  496  18-Sep-08  11019.69  4806.292767  3878.771078  11658.00254   
497  497  19-Sep-08  11388.44  5269.607790  4246.994928  11878.44496   
498  498  22-Sep-08  11015.69  5227.512359  4214.237071  12049.82757   
499  499  24-Sep-08  10825.17  5109.668623  4113.333213  12159.59156   
500  500  25-Sep-08  11022.06  5197.000000  4226.810000  12006.53000   

      djiaRet  djiaForecast  
0         NaN           NaN  
1    0.995919  10977.075328  
2    0.991282  10925.971020  
3    1.004351  11070.014536  
4    0.996732  10986.044308  
..        ...           ...  
496  1.038647  11448.027963  
497  1.033463  11390.889307  
498  0.967269  10661.301822  
499  0.982705  10831.429829  
500  1.018188  11222.531068  

[501 rows x 8 columns]

Repeat for the other three assets in our portfolio:

In [31]:
Data['ftseRet'] = Data['FTSE-500']/Data['FTSE-500'].shift(1)
Data['ftseForecast'] = Data['FTSE-500'][500] * Data['ftseRet']
Data['cacRet'] = Data['CAC-40']/Data['CAC-40'].shift(1)
Data['cacForecast'] = Data['CAC-40'][500] * Data['cacRet']
Data['nikkeiRet'] = Data['Nikkei']/Data['Nikkei'].shift(1)
Data['nikkeiForecast'] = Data['Nikkei'][500] * Data['nikkeiRet']
Data.tail()


row       date      DJIA     FTSE-500       CAC-40       Nikkei  \
496  496  18-Sep-08  11019.69  4806.292767  3878.771078  11658.00254   
497  497  19-Sep-08  11388.44  5269.607790  4246.994928  11878.44496   
498  498  22-Sep-08  11015.69  5227.512359  4214.237071  12049.82757   
499  499  24-Sep-08  10825.17  5109.668623  4113.333213  12159.59156   
500  500  25-Sep-08  11022.06  5197.000000  4226.810000  12006.53000   

      djiaRet  djiaForecast   ftseRet  ftseForecast    cacRet  cacForecast  \
496  1.038647  11448.027963  1.006572   5231.156658  1.002240  4236.276372   
497  1.033463  11390.889307  1.096398   5697.978257  1.094933  4628.074272   
498  0.967269  10661.301822  0.992012   5155.484585  0.992287  4194.207833   
499  0.982705  10831.429829  0.977457   5079.844104  0.976056  4125.605101   
500  1.018188  11222.531068  1.017091   5285.823992  1.027588  4343.417334   

     nikkeiRet  nikkeiForecast  
496   0.976618    11725.795841  
497   1.018909    12233.562763  
498   1.014428    12179.760625  
499   1.009109    12115.899585  
500   0.987412    11855.395136

The 500 possible final portfolio values and the `loss` (negative of gains):

In [38]:
4000*Data['djiaForecast']/Data['DJIA'][500]
3000*Data['ftseForecast']/Data['FTSE-500'][500]
1000*Data['cacForecast']/Data['CAC-40'][500]
2000*Data['nikkeiForecast']/Data['Nikkei'][500]
4000*Data['djiaForecast']/Data['DJIA'][500] + 3000*Data['ftseForecast']/Data['FTSE-500'][500] + 1000*Data['cacForecast']/Data['CAC-40'][500] + 2000*Data['nikkeiForecast']/Data['Nikkei'][500]

0               NaN
1      10014.333846
2      10027.481312
3       9946.735942
4       9974.860634
           ...     
496    10129.780586
497    10555.795412
498     9866.255623
499     9857.464506
500    10126.438966
Length: 501, dtype: float64

In [40]:
Data['pValue'] = 4000*Data['djiaForecast']/Data['DJIA'][500] + 3000*Data['ftseForecast']/Data['FTSE-500'][500] + 1000*Data['cacForecast']/Data['CAC-40'][500] + 2000*Data['nikkeiForecast']/Data['Nikkei'][500]
Data['loss'] = -(Data['pValue'] - 10000)
Data.tail()

row       date      DJIA     FTSE-500       CAC-40       Nikkei  \
496  496  18-Sep-08  11019.69  4806.292767  3878.771078  11658.00254   
497  497  19-Sep-08  11388.44  5269.607790  4246.994928  11878.44496   
498  498  22-Sep-08  11015.69  5227.512359  4214.237071  12049.82757   
499  499  24-Sep-08  10825.17  5109.668623  4113.333213  12159.59156   
500  500  25-Sep-08  11022.06  5197.000000  4226.810000  12006.53000   

      djiaRet  djiaForecast   ftseRet  ftseForecast    cacRet  cacForecast  \
496  1.038647  11448.027963  1.006572   5231.156658  1.002240  4236.276372   
497  1.033463  11390.889307  1.096398   5697.978257  1.094933  4628.074272   
498  0.967269  10661.301822  0.992012   5155.484585  0.992287  4194.207833   
499  0.982705  10831.429829  0.977457   5079.844104  0.976056  4125.605101   
500  1.018188  11222.531068  1.017091   5285.823992  1.027588  4343.417334   

     nikkeiRet  nikkeiForecast        pValue        loss  
496   0.976618    11725.795841  10129.780586 -129.780586  
497   1.018909    12233.562763  10555.795412 -555.795412  
498   1.014428    12179.760625   9866.255623  133.744377  
499   1.009109    12115.899585   9857.464506  142.535494  
500   0.987412    11855.395136  10126.438966 -126.438966

Now just consider the variable `loss`:

In [45]:
Loss = Data[['row', 'loss']]
Loss.sort_values(by=['loss'], ascending=False)

row        loss
494  494  477.841000
339  339  345.435075
349  349  282.203845
329  329  277.041294
487  487  253.384956
..   ...         ...
341  341 -307.930115
377  377 -316.489338
379  379 -333.021840
497  497 -555.795412
0      0         NaN

[501 rows x 2 columns]

Find the 1% top highest or the 99th percentile:

In [46]:
import scipy.stats as scs
scs.scoreatpercentile(Loss['loss'], 99)

253.38495634799074

The ten-day 99% VaR: $VaR_{1-day} \times \sqrt{10}$

In [47]:
import numpy as np
253.38495634799074 * np.sqrt(10)

801.2735868819912

# 2. Model-Building approach

## One-asset

This approach relies on the property that 99% certain that a normally distributed random variable will not decrease by more than 2.326 standard deviations. So the one-day 99% VaR is:

$$\sigma * 2.326$$

So we just need to calculate the historical volatility and use the above formula.

## Generalization of many-assets case

The variance of the portfolio equals:

$$\sigma_p^2 = \alpha^T C \alpha$$

Thus, it is better to use the matrix calculation to solve the problem. Let's consider an easy example with only two assets:

In [59]:
alpha = np.array([10, 5])
C = np.array([[0.02*0.02, 0.02*0.01*0.3], [0.02*0.01*0.3, 0.01*0.01]])

In [60]:
alpha

array([10,  5])

In [61]:
C

array([[4.e-04, 6.e-05],
       [6.e-05, 1.e-04]])

In [62]:
alpha.T

array([10,  5])

In [63]:
alpha.T.dot(C)

array([0.0043, 0.0011])

In [66]:
var_p = alpha.T.dot(C).dot(alpha) # variance
var_p

0.048499999999999995

In [67]:
np.sqrt(var_p) # standard deviation

0.2202271554554524

The ten-day 99% VaR is:

In [68]:
2.326 * np.sqrt(var_p) * np.sqrt(10)

1.6198715566365132